FROM alpine
RUN apk add nodejs npm
RUN addgroup -S expressgroup
RUN adduser -S express -G expressgroup

WORKDIR /app
COPY package*.json ./
RUN npm install

USER express
COPY . .
EXPOSE 3000/tcp
CMD ["node", "start"]