FROM node:19-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install -g typescript
COPY . .
RUN ["npm", "run", "build"]

FROM node:19-alpine
RUN addgroup -S expressgroup
RUN adduser -S express -G expressgroup
WORKDIR /app
COPY --from=builder /app/package.json ./
RUN npm install --only=production
USER express
COPY --from=builder /app/build ./build
EXPOSE 3000/tcp
CMD ["node", "start"]

# PS : Je sais que je ne suis pas censé faire ça, 
# mais je n'ai pas réussi à faire fonctionner le build
# sans installer séparément typescript,
# je n'ai pas trouvé de moyen de l'installer en même temps que les autres dépendances,
# cela pourrait de NODE_ENV mais impossible de le corriger